### PR TITLE
Add Terminal by JD Hartley to clock face list

### PR DESCRIPTION
**Pull request by jdhartley**

### CODE REVIEW

**Comment by orviwan** [comment]
Sorry, the list is alphabetical. Can you fix please?

**Comment by jdhartley** [comment]
@orviwan I think it is in the right spot alphabetically (just confusingly so) — let me know if you guys want to consider the capital H of "TH3" to come after the lowercase "e" in Terminal though

**Comment by orviwan** [comment]
I think just consistent with the rest of the list, so ignoring the fact the second letter is uppercase. Thanks

**Comment by jdhartley** [comment]
@orviwan no problem, thanks for clarifying! Should be good to go now

**Pull request merged**
